default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: tzanarde
  password: tzanarde
  pool: 5

development:
  <<: *default
  database: reembolso_app_development

test:
  <<: *default
  database: reembolso_app_test

production:
  <<: *default
  database: reembolso_app_production
  username: tzanarde
  password: tzanarde
